Bugfix/bigdecimal trimming bug
ingzkp/kotlinx-serialization-bfl pull request #19
Opened 2021-04-02 12:02 UTC by peterpaul

2021-04-02 13:17 UTC, SereV94 commented on src/main/kotlin/com/ing/serialization/bfl/serializers/BigDecimalSerializer.kt
> +                ByteArray(FRACTION_SIZE - (fractionalPart?.length ?: 0)) { 0 }
2 comments:
- You need to wrap line 56 (before +) in parentheses otherwise the null-safety operator (?:) will include both emptyByteArray() and the part in line 57
- Personally, I would inverse the operands in the addition so that we maintain coherency on how we build up the integer and fractional parts (and in that case change trimEnd to trimStart in line 33)

2021-04-02 13:18 UTC, SereV94 commented on src/main/kotlin/com/ing/serialization/bfl/serializers/BigDecimalSerializer.kt
> +        val integer = this.integer.joinToString(separator = "") { "$it" }.trimStart('0')
Nice catch 👍

2021-04-02 13:32 UTC, SereV94 commented on src/test/kotlin/com/ing/serialization/bfl/serde/serializers/custom/BigDecimalSerializerTest.kt
> +
Again personal preference: I would merge these 2 tests (since they are testing the same functionality on different bigDecimals) and have something like:
```suggestion
    @Test
    fun `serialize and deserialize BigDecimals() {
        listOf(
             Data(BigDecimal.TEN),
             Data(BigDecimal("0.01")),
        ).forEach {
            roundTripInlined(it)
            roundTrip(it, it::class)
        }
    }

```

2021-04-02 13:38 UTC, peterpaul commented on src/main/kotlin/com/ing/serialization/bfl/serializers/BigDecimalSerializer.kt
> +                ByteArray(FRACTION_SIZE - (fractionalPart?.length ?: 0)) { 0 }
Good catch! I fixed the first part, the second part will actually fail the tests, because this is a matter of ordering in the bytearray. So the fraction part has to be postfixed with zeros, while the integer part has to be prefixed with zeroes.

2021-04-02 13:49 UTC, peterpaul commented on src/test/kotlin/com/ing/serialization/bfl/serde/serializers/custom/BigDecimalSerializerTest.kt
> +
Done, I even combined it with the test before these.

2021-04-02 19:14 UTC, vnermolaev requested changes

2021-04-02 19:14 UTC, vnermolaev commented on src/main/kotlin/com/ing/serialization/bfl/serializers/BigDecimalSerializer.kt
> +        private fun emptyByteArray(): ByteArray = ByteArray(0) { 0 }
What's the point of this function? it adds neither extra clarity nor shortens the notation. This function is superfluous, you can just write `ByteArray(0)`

2021-04-02 19:14 UTC, vnermolaev commented on src/main/kotlin/com/ing/serialization/bfl/serializers/BigDecimalSerializer.kt
> +            val fraction = (fractionalPart?.toListOfDecimals() ?: emptyByteArray()) +
oh yes, this was indeed wrong.

2021-04-02 19:14 UTC, vnermolaev commented on src/main/kotlin/com/ing/serialization/bfl/serializers/BigDecimalSerializer.kt
> +        private fun String.toListOfDecimals(): ByteArray {
how about a more concise version?
```kotlin
private fun String.tolListOfDecimals() = map { ... }.toByteArray()
```

2021-04-02 19:14 UTC, vnermolaev commented on src/main/kotlin/com/ing/serialization/bfl/serializers/BigDecimalSerializer.kt
> +    init {
this is good.

2021-04-04 09:59 UTC, vnermolaev approved these changes

2021-04-04 09:59 UTC, merged

2021-04-04 10:00 UTC, vnermolaev commented
I took the liberty to merge the PR.