Feature/instructive errors
ingzkp/kotlinx-serialization-bfl pull request #20
Opened 2021-04-02 15:16 UTC by mvdbos

This PR adds a property `Element.propertyName` which is used to produce more instructive error messages so that the user can more easily determine where to fix the error.

2021-04-02 19:03 UTC, vnermolaev requested changes

2021-04-02 19:03 UTC, vnermolaev commented on src/main/kotlin/com/ing/serialization/bfl/serde/element/PrimitiveElement.kt
> +        if (kind !is PrimitiveKind) throw SerdeError.NonPrimitive(kind)
this is not true, because `String` is also a `PrimitiveKind`. Strings are handled separately.

2021-04-02 19:27 UTC, mvdbos commented on src/main/kotlin/com/ing/serialization/bfl/serde/element/PrimitiveElement.kt
> +        if (kind !is PrimitiveKind) throw SerdeError.NonPrimitive(kind)
Ah, I missed that, will add that to the condition.

2021-04-02 19:36 UTC, mvdbos commented on src/main/kotlin/com/ing/serialization/bfl/serde/element/PrimitiveElement.kt
> +        if (kind !is PrimitiveKind) throw SerdeError.NonPrimitive(kind)
Fixed

2021-04-04 10:12 UTC, vnermolaev approved these changes
Good first issue! 🥇 :)

2021-04-04 10:12 UTC, merged

2021-04-04 10:12 UTC, vnermolaev commented
I took the liberty to merge.