Feature/handle polymorphic
ingzkp/kotlinx-serialization-bfl pull request #48
Opened 2021-05-11 13:23 UTC by SereV94

Main changes introduced:
- Allow **only one subtype of a polymorphic** at any nesting level within a structure or a collection
- Add support for **nullable polymorphic**
- Remove delegation from the instantiation of polymorphic serializers (**inherit directly from SurrogateSerializer** instead)

2021-05-12 13:06 UTC, vnermolaev requested changes

2021-05-12 13:06 UTC, vnermolaev commented on src/main/kotlin/com/ing/serialization/bfl/serde/element/ElementFactory.kt
> +                val children = mutableListOf(
you could use some spacing in-between less related lines.

2021-05-12 13:06 UTC, vnermolaev commented on src/main/kotlin/com/ing/serialization/bfl/serde/element/StructureElement.kt
> +import com.ing.serialization.bfl.serde.SerdeError
I think it is better to have a separate `PolymorphicStructureElement`, now you have not only an extra field but a specific `decodePolymorphicNull` method which is quite meaty.

2021-05-12 13:08 UTC, vnermolaev commented on src/main/kotlin/com/ing/serialization/bfl/serde/Utils.kt
> +        if (isPolymorphic && inner.last().serialName != other.inner.last().serialName) {
this can be scheduled for the next PR.

2021-05-12 13:11 UTC, vnermolaev commented
Good work. Let's add some polish to make it shine :)

2021-05-12 13:11 UTC, SereV94 commented on src/main/kotlin/com/ing/serialization/bfl/serde/element/ElementFactory.kt
> +    @Suppress("ComplexMethod", "LongMethod", "NestedBlockDepth")
Yes, it is... Maybe I could create separate functions for collections and polymorphic, since these 2 cases occupy most lines

2021-05-12 13:14 UTC, SereV94 commented on src/main/kotlin/com/ing/serialization/bfl/serde/FixedLengthStructureProcessor.kt
> +            queue.prepend(schedulable)
Because initially there is the inner placeholder element in the queue... So, after resolution we remove it from the queue (line 45) and push the resolved inner StructureElement in its place (line 46)

2021-05-12 13:16 UTC, SereV94 commented on src/main/kotlin/com/ing/serialization/bfl/serde/Utils.kt
> + * Extension function used for resolving the inner StructureElement of a polymorphic when its actual type is available
Indeed, the docStrings need to be improved. What we do have at that point is the correct descriptor of the inner StructureElement of the polymorphic. I will update the description of the function

2021-05-12 13:25 UTC, SereV94 commented on src/main/kotlin/com/ing/serialization/bfl/serde/element/StructureElement.kt
> +import com.ing.serialization.bfl.serde.SerdeError
I am not sure that this option would improve code quality, because the variable `isPolymorphic` used currently to denote a polymorphic Element, is defined on `Element`, giving us a lot of flexibility in the declaration of functions operating on `Elements`. If we have a dedicated `PolymorphicStructureElement`, then the above flag is not needed, and explicit casting is needed before calling functions that exist only for `PolymorphicStructureElement`

Long story short, we can do it but I am not sure if it is indeed beneficial

2021-05-12 13:26 UTC, SereV94 commented on src/main/kotlin/com/ing/serialization/bfl/serde/Utils.kt
> +        if (isPolymorphic && inner.last().serialName != other.inner.last().serialName) {
It's doable. Shall I include it in this PR or handle it in a separate one?

2021-05-12 13:28 UTC, SereV94 commented on src/main/kotlin/com/ing/serialization/bfl/serde/element/ElementFactory.kt
> +                        it.filterIsInstance<Pair<*, *>>().unzip().toList()
I am not sure that I understand the question. Are you referring to doing this special handling for Maps and Lists within `convertToList` instead of `ElementFactory`?

2021-05-12 13:30 UTC, vnermolaev commented on src/main/kotlin/com/ing/serialization/bfl/serde/Utils.kt
> +        if (isPolymorphic && inner.last().serialName != other.inner.last().serialName) {
Let's do it in the next one, there are other smaller improvements.

2021-05-12 13:31 UTC, vnermolaev commented on src/main/kotlin/com/ing/serialization/bfl/serde/element/ElementFactory.kt
> +                        it.filterIsInstance<Pair<*, *>>().unzip().toList()
`is MutableMap<*, *> -> this.toList().unzip().toList()`
in `fun <T> T.convertToList()`

2021-05-12 13:34 UTC, vnermolaev commented on src/main/kotlin/com/ing/serialization/bfl/serde/FixedLengthStructureProcessor.kt
> +            queue.prepend(schedulable)
Ah, I see. Please add comment `Replace ...`

2021-05-12 13:38 UTC, vnermolaev commented on src/main/kotlin/com/ing/serialization/bfl/serde/element/StructureElement.kt
> +import com.ing.serialization.bfl.serde.SerdeError
well, `PolymorphicStructureElement` is still an `Element` you can pass it in any function accepting `Element` without extra cast.
Flag `isPolymorphic` for any `element: Element` is easily reproduced `element is PolymorphicStructureElement`.

2021-05-12 13:46 UTC, SereV94 commented on src/main/kotlin/com/ing/serialization/bfl/serde/element/ElementFactory.kt
> +                        it.filterIsInstance<Pair<*, *>>().unzip().toList()
Indeed, this can be incorporated in `convertToList` and it would simplify the collection handling in ElementFactory. Nevertheless, `convertToList` would need to return a List of Lists in that case. If this is fine, I can easily make this change

2021-05-12 13:49 UTC, SereV94 commented on src/main/kotlin/com/ing/serialization/bfl/serde/element/StructureElement.kt
> +import com.ing.serialization.bfl.serde.SerdeError
Indeed, but consider the function `verifyResolvabilityOrThrow` defined on `Element`. This function is needed to see whether a nullable `Element` containing a polymorphic can be resolved. If we go with your suggestion, then we would refer to a subclass (`PolymorphicStructureElement`) within the base class (`Element`)

2021-05-12 13:55 UTC, vnermolaev commented on src/main/kotlin/com/ing/serialization/bfl/serde/element/StructureElement.kt
> +import com.ing.serialization.bfl.serde.SerdeError
I am not sure what the problem is.
```kotlin
fun verifyResolvabilityOrThrow(): Element {
        // if a null polymorphic has not been resolved in the parsing stage, an exception is thrown
        if (isNull && this is PolymorphicStructureElement) {
            throw SerdeError.NonResolvablePolymorphic(serialName)
        }
        // check also the children of the element for resolvability
        inner.forEach { it.verifyResolvabilityOrThrow() }
        return this
    }
```

2021-05-17 07:35 UTC, vnermolaev requested changes

2021-05-17 07:35 UTC, vnermolaev commented on src/main/kotlin/com/ing/serialization/bfl/serde/BinaryFixedLengthInputDecoder.kt
> +            if (it is PolymorphicStructureElement) it.decodeNull(input, serializersModule)
is it reasonable to unify `decodeNull` for all kinds of elements? i.e., `decodeNull(input: DataInputStream, serializersModule: SerializersModule = EmptySerializersModule)`. In this case, we can simplify the flow a bit.

2021-05-17 07:35 UTC, vnermolaev commented on src/main/kotlin/com/ing/serialization/bfl/serde/FixedLengthStructureProcessor.kt
> +            // replace the placeholder StructureElement from queue with the populated version
maybe we can still replace the following the two next lines with a devoted ext function `reschedule(schedulable)` on `ArrayDeque` which would replace the first. Then the code is more self-explanatory.

2021-05-17 07:35 UTC, vnermolaev commented on src/main/kotlin/com/ing/serialization/bfl/serde/element/ElementFactory.kt
> +        // use reflection to treat non-null collection data
why is this comment here? seems an artefact from the prev version.

2021-05-17 07:38 UTC, SereV94 commented on src/main/kotlin/com/ing/serialization/bfl/serde/element/ElementFactory.kt
> +        // use reflection to treat non-null collection data
True, I will remove it

2021-05-17 07:39 UTC, SereV94 commented on src/main/kotlin/com/ing/serialization/bfl/serde/FixedLengthStructureProcessor.kt
> +            // replace the placeholder StructureElement from queue with the populated version
We can. I will address it

2021-05-17 07:44 UTC, SereV94 commented on src/main/kotlin/com/ing/serialization/bfl/serde/BinaryFixedLengthInputDecoder.kt
> +            if (it is PolymorphicStructureElement) it.decodeNull(input, serializersModule)
Your suggestion would indeed simplify these lines, but I think that it would produce confusion when checking the definition of all the other elements apart from PolymorphicStructureElement, since serializersModule will be unused for them.

2021-05-17 08:28 UTC, vnermolaev approved these changes

2021-05-17 08:31 UTC, merged